### ISSUE TITLE
Unable to handle `~`

### ISSUE THREAD

**Issue by buhtzz** [earnestt1234/seedir#19]
The path `~` is not resolved to `$HOME`.

```
>>> seedir.seedir('~')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/seedir/realdir.py", line 336, in seedir
    s = RealDirStructure(path,
  File "/home/user/.local/lib/python3.9/site-packages/seedir/folderstructure.py", line 218, in __call__
    return self._folderstructure(folder, **kwargs).strip()
  File "/home/user/.local/lib/python3.9/site-packages/seedir/folderstructure.py", line 122, in _folderstructure
    listdir = self.listdir(folder)
  File "/home/user/.local/lib/python3.9/site-packages/seedir/folderstructurehelpers.py", line 87, in listdir_fullpath
    return [os.path.join(path, f) for f in os.listdir(path)]
FileNotFoundError: [Errno 2] No such file or directory: '~'
```

I assume `os.path.realpath()` would help here.
But my advise would be to drop the use of `os.path` and switch to more modern and Python's own `pathlib`.

**Comment by earnestt1234** [comment]
Yes, I agree this would be nice.  Seems `os.path.exapanduser()` is needed actually.  I think adding a line to concert the input to and absolute, user-expanded path would be the fix.  Will add this, pending some of the input parsing proposed in #20.

**Comment by buhtzz** [comment]
I would recommend using the high-level API `pathlib.Path.resolve()` instead of low-level `os.path`.

**Comment by earnestt1234** [comment]
Sure!  Wasn't aware of that, thanks

**Comment by earnestt1234** [comment]
This has been added in [v0.4.0](https://github.com/earnestt1234/seedir/releases/tag/v0.4.0).  Both string paths and pathlib objects will be expanded and resolved automatically,  now
